# ZEO Composable MCP Server - Cloudflare Workers Configuration

name = "zeo-composable-mcp"
main = "dist/zeo-mcp-server.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
ZEO_VERSION = "1.0.0"
ZEO_ENVIRONMENT = "development"

# KV Namespace for persistent memory and caching
[[kv_namespaces]]
binding = "ZEO_KV"
id = "9bd4be6be50540c4bd4fc36a86472421"

# D1 Database for structured data storage
[[d1_databases]]
binding = "ZEO_DB"
database_name = "zeo-composable-db"
database_id = "9f403f70-7a82-47aa-8ca0-5b9aa2e09163"

# R2 Bucket for file storage and large objects
[[r2_buckets]]
binding = "ZEO_BUCKET"
bucket_name = "zeo-composable-storage"

# AI binding for Cloudflare AI
[ai]
binding = "AI"

# Build configuration
[build]
command = "npm run build"
cwd = "."

# Worker limits and configuration
[limits]
cpu_ms = 30000  # 30 seconds max execution

# Usage monitoring
[observability]
enabled = true
head_sampling_rate = 0.01