name = "zeo-composable-mcp"
main = "src/zeo-mcp-server.ts"
compatibility_date = "2024-11-01"
node_compat = true

# Example configuration - copy to wrangler.toml and fill in your values

[env.staging]
name = "zeo-composable-mcp-staging"

[env.staging.vars]
GITHUB_TOKEN = "your_github_token_here"

[[env.staging.d1_databases]]
binding = "D1_DATABASE"
database_name = "zeo-staging"
database_id = "your_d1_database_id_here"

[[env.staging.kv_namespaces]]
binding = "KV_STORAGE"
id = "your_kv_namespace_id_here"

[[env.staging.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "zeo-files-staging"

[env.staging.ai]
binding = "AI"

[env.production]
name = "zeo-composable-mcp-prod"

[env.production.vars]
GITHUB_TOKEN = "your_production_github_token"

[[env.production.d1_databases]]
binding = "D1_DATABASE"
database_name = "zeo-production"
database_id = "your_production_d1_id"

[[env.production.kv_namespaces]]
binding = "KV_STORAGE"
id = "your_production_kv_id"

[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "zeo-files-production"

[env.production.ai]
binding = "AI"